version: "3.8"

services:
  db:
    container_name: demo_db
    image: postgres:14-alpine3.17
    ports:
      - ${PGPORT}:${PGPORT}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGPORT: ${PGPORT}
  backend:
    container_name: demo_backend
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    image: demo_backend:latest
    depends_on:
      - db
    env_file: .env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
volumes:
  postgres-data:
