[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
profile = "black"

[tool.black]
line-length = 88

[tool.pytest.ini_options]
testpaths = ["/tests"]
